ALTER TABLE budget ADD COLUMN IF NOT EXISTS month TEXT;
UPDATE budget SET month = TO_CHAR(updated_at AT TIME ZONE 'UTC', 'YYYY-MM') WHERE month IS NULL;
ALTER TABLE budget ALTER COLUMN month SET NOT NULL;
ALTER TABLE budget ALTER COLUMN month SET DEFAULT TO_CHAR(NOW() AT TIME ZONE 'UTC', 'YYYY-MM');
